### ISSUE TITLE
[BEDROCK EDITION] WORLDS DO NOT OPEN WITH THE PROGRAM

### ISSUE THREAD

**Issue by merrysc23** [tryashtar/image-map#100]
Hello, I wanted to comment on my problem, when I open the program I cannot run my world in Bedrock Edition, please I would like a solution, since there are programs as good as this one.

**That is my world**
https://drive.google.com/drive/folders/1-UqK2fZB708yqcHPxmdolVbh5Lmw740e?usp=sharing

![image](https://user-images.githubusercontent.com/109096641/179527410-9ded262f-8aa4-4c0e-a5c6-408ddf530535.png)

**Comment by merrysc23** [comment]
@tryashtar

**Comment by merrysc23** [comment]
> Lo siento, amigo, ese error proviene de leveldb, que casi no puedo entender, y mucho menos diagnosticar o corregir. desearía poder ayudar

:(

**Comment by merrysc23** [comment]
Hey my friend

**Comment by merrysc23** [comment]
i need your help @tryashtar

**Comment by merrysc23** [comment]
@tryashtar What happens is that I formatted my computer by mistake and currently I lost my minecraft world that I have so fondly that my girlfriend and I did :(

**Comment by merrysc23** [comment]
@tryashtar I would like to know if you downloaded it at the time and if you will have it saved please :(

I am really very sad because I did it with a lot of love and I hate myself so much for not keeping it please friend I ask it with all my heart if you have it there or can you recover it I would really appreciate it

**Comment by merrysc23** [comment]
@tryashtar Please I just want to be happy for the new year :(

**Comment by tryashtar** [comment]
Oh no! So sorry to hear that!! :(
I looked for your world on my computer, and ran a scan for deleted files, but I'm afraid I couldn't find any sign of it... I know what it's like to lose a Minecraft world, I really hope you can get it back somehow!

**Comment by merrysc23** [comment]
> ¡Oh, no! ¡¡Lamento tanto oír eso!! :( Busqué tu mundo en mi computadora y realicé un escaneo en busca de archivos eliminados, pero me temo que no pude encontrar ninguna señal de él... Sé lo que es perder un mundo de Minecraft, realmente espero ¡Puedes recuperarlo de alguna manera!

the world was called "Mundito" you can't find it :'( it's from the bedrock edition version
