### ISSUE TITLE
Will not open on Windows 11.

### ISSUE THREAD

**Issue by Laqota** [tryashtar/image-map#102]
The application version 4, and above does not seem to open at all. But version 3 opens and works but I want an updated version.

I am using a x64 version system.

**Comment by tryashtar** [comment]
This is a bit strange, as I use Windows 11

4+ requires .NET 6, do you have that installed?

**Comment by Kyoko92** [comment]
hi, i have the same problem. Windows 11 Pro 21H2 x64. All Windows updates installed.

and net. Framework 6.0.8 (Desktop x64) installed.

**Comment by Clumsycows** [comment]
I upgraded from windows 10 to 11 and the application was gone. I re-downloaded it attempted to run it but I keep getting the .NET isn't installed which it is and it's on 6.0

**Comment by Clumsycows** [comment]
I would like to provide an update on this issue, you need to install the dotnet 6.0 sdk. You can get that here --> https://dotnet.microsoft.com/en-us/download/visual-studio-sdks if you need more information on what version of dotnet is installed go to command prompt and type "dotnet --info" hope this helps :)
