### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Alphastein2021** [tryashtar/image-map#109]
@tryashtar 

Image Map 4.2.2

Crash Report:
https://github.com/tryashtar/image-map/files/9664528/crash-2022-09-28_13.44.05.txt

**Comment by tryashtar** [comment]
Please try [4.2.3](https://github.com/tryashtar/image-map/releases/tag/v4.3.3) and let me know if this fixes your crash :)

**Comment by Alphastein2021** [comment]
@tryashtar 4.2.3 is working now. Thank you!
