### ISSUE TITLE
ability to include map files in structure file

### ISSUE THREAD

**Issue by MagerKaos** [tryashtar/image-map#116]
I would like to suggest adding the ability to include the map entities in the structure block or maybe they would have to be in a behavior pack or resource pack, I am not sure.  I am using Bedrock and I would like to be able to share the structure file in an mcpack file with others so they can import it into their world.  When I share it now, all the maps in the item frames are blank because the individual maps are not loaded with the structure block.  I can't find a way to get the map files out of the world that ImageMap loaded them in to.

**Comment by tryashtar** [comment]
Unfortunately Bedrock does make this easy. The only place map data can go is embedded in the world data, inaccessible to almost anyone. I can consider adding a function to transfer maps between worlds, but that won't make the structures any more shareable.
