### ISSUE TITLE
Bedrock Crashing Error

### ISSUE THREAD

**Issue by BILLYMAXTED** [tryashtar/image-map#119]
When i click on my world it comes up with a big paragraph then i import my pictures then i sent them all to world and the software just keeps crashing

**Comment by tryashtar** [comment]
Please show me a screenshot of this crash message

**Comment by BILLYMAXTED** [comment]
***@***.***
I click on one of my bedrock worlds and it shows this image then I click on it again and then it lets me so then when I import the pictures and click send all to world it doesn’t say anything it just loads and crashes ???

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by tryashtar** [comment]
Sorry, I can't see your pictures :/

**Comment by BILLYMAXTED** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by BILLYMAXTED** [comment]
https://drive.google.com/file/d/1z5E-WRo5TBqHfW7mTNPWx2o6h1WFFi_L/view?usp=sharing

Link to the the image

**Comment by tryashtar** [comment]
Thanks. Definitely try unzipping the zip and running it from that folder instead of clicking inside the zip. Let me know if it helps

**Comment by BILLYMAXTED** [comment]
its worked thank you for helping its an amazing mod btw
