### ISSUE TITLE
Image map creation for essential mod not giving structure item

### ISSUE THREAD

**Issue by Razor7100** [tryashtar/image-map#125]
I followed the steps to create an image map on my world. I chose the saves folder as the target location and imported my images to my world however, I did not get the generate structure item in my inventory. What can I do to solve this issue?
I am using [essential mod](https://essential.gg/) java version

**Comment by awakedlost** [comment]
what tutorial u followed ?

**Comment by Razor7100** [comment]
What do you mean? I clicked generate structure and upload to world

**Comment by Razor7100** [comment]
Still not working
