### ISSUE TITLE
how to import image into world

### ISSUE THREAD

**Issue by cursorguy** [tryashtar/image-map#134]
instructions are vague, I uploaded my image and set how many maps I want, then I selected all my maps and hit generate structure which then gave me a structure block in my inventory (like the instructions state). However, when I hit the load button, the text on the bottom left says it loaded and I hear a sound but I see nothing. What am I doing wrong? For the record I've tried it on a structure with frames, one without frames, and with no structure at all.

**Comment by tryashtar** [comment]
What version of Minecraft are you using?

**Comment by cursorguy** [comment]
1.20.4 i believe, whatever the newest non-beta release is

**Comment by cursorguy** [comment]
I did notice that item frames do generate on the wall, however they are invisible

**Comment by tryashtar** [comment]
Can you upload a zip of your world for me to look at? :)

**Comment by cursorguy** [comment]
I'm so dumb, I had the "invisible" box checked. Sorry for wasting your time

**Comment by tryashtar** [comment]
Hehe very good, let me know if you have any other issues or questions
