### ISSUE TITLE
Not available in 1.20.6

### ISSUE THREAD

**Issue by wslst250** [tryashtar/image-map#137]
When` I got everything done and entered the game, I found that there was just a normal Structure Block in my inventory.There was nothing in the Structure Block
These two screenshots illustrate the problem。
The first photo is based on 1.20.4, which is normal。
https://www.wslst.xyz/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE2024-06-07-232550.png
The second photo is from 1.20.6, where the Structure Block is no longer usable。
https://www.wslst.xyz/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE2024-06-07-232602.png

**Comment by tryashtar** [comment]
Thank you for the report. It's difficult for me to make changes to the project at this point, but I *will* fix this.

**Comment by tryashtar** [comment]
Note to self: two different things changed at separate times, the item component format (for both the structure block item and map items) and the generated structure directory

**Comment by wslst250** [comment]
It seems like this issue is troublesome, so is there anything I can do now to reimplement the functionality of the software?

**Comment by tryashtar** [comment]
Done! https://github.com/tryashtar/image-map/releases/tag/v4.2.6
