### ISSUE TITLE
The given key was not present in the dictionary when load world

### ISSUE THREAD

**Issue by theogiraudet** [tryashtar/image-map#21]
![image](https://user-images.githubusercontent.com/28688370/44619547-a0b47600-a888-11e8-8b64-f6882a5e4790.png)

**Comment by tryashtar** [comment]
Did you have a level.dat in the world?

**Comment by tryashtar** [comment]
I updated it today. When you get back home, re-download again, try it and let me know :)

**Comment by theogiraudet** [comment]
Okay!
