### ISSUE TITLE
Minecraft Education edition root folder

### ISSUE THREAD

**Issue by thecommonpeople** [tryashtar/image-map#30]
Hey, I would like to Open Edu folder destination so add maps to those worlds - currently, I have to swap world folders to Bedrock and the back again location is in packages just called Microsoft.MinecraftEducationEdition_xxxxxxxx

**Comment by tryashtar** [comment]
Hmm... I might make it "remember" your bedrock saves location just like it does now for java. Would this work for you?

**Comment by tryashtar** [comment]
There is now a "browse" button in the bedrock dialog so you can choose your desired folder, and it will remember it between sessions
