### ISSUE TITLE
worked for version 1.13.2 but the update to 1.14 broke chests, theyr empty

### ISSUE THREAD

**Issue by xbuttercupx** [tryashtar/image-map#32]
worked for version 1.13.2 but the update to 1.14 broke chests, theyr empty

**Comment by xbuttercupx** [comment]
a bit of context - i used this for a server back in 1.13 and it worked amazing.. but now it just doesnt..idk what to do to try fix this but all the so called sites that do what this app does are BS theyr colours are bland and they seem to hav phat borders on the images etc

**Comment by xbuttercupx** [comment]
(( its a personal server ))

**Comment by tryashtar** [comment]
Hmm... it seems to work for me fine in 1.14.3-pre2. Although I'm testing on a singleplayer world. For a server, you might have to pick your UUID on the existing maps tab. Though if it worked in 1.13, it seems like it probably would in 1.14 as well. I'm not sure...
