### ISSUE TITLE
Add Floyd-Steinberg dithering

### ISSUE THREAD

**Issue by Leo-Chong** [tryashtar/image-map#36]
Please add Floyd-Steinberg dithering therefore the image can have better quality. Thx!

**Comment by tryashtar** [comment]
Will be java-only since bedrock has full colors

**Comment by tryashtar** [comment]
![image](https://user-images.githubusercontent.com/26075577/60409466-f6c90880-9b80-11e9-8752-c9fd40b3000a.png)
Looks pretty good I'd say
