### ISSUE TITLE
Add Custom Numbering the Maps & Select Multiple Files

### ISSUE THREAD

**Issue by Leo-Chong** [tryashtar/image-map#40]
Hi again,

I need a feature that when people click the 'Send All to' button, they can enter the number that they want (e.g. the last map is 'map_10' but you can ignore and numbering it to 'map_18') and not only auto numbering to last number.

Also when I try to export a lot of existing map to images, I found that I need to click one by one. Please add feature about select multiple files like click the first item, hold the shift key, click the last item for select multiple files.

My English is not really well so you don't understand what I want to, ask me.

Thank you for your useful program and your patience!

**Comment by tryashtar** [comment]
Hm, I've been planning some ID stuff for a while (#18), but have not understood the use case well enough to plan out the most convenient option.

How does this sound:
1. Select any number of maps
2. Right-click to open ID dialog
3. Type in new ID
4. First map gets this ID, second gets this ID+1, etc.
5. If a map in the import area has the same ID as an existing map, it gets a different background color to signify it will overwrite the one in the world

The mass-select thing should be easy-enough to do

**Comment by tryashtar** [comment]
This is now released, let me know what you think: https://github.com/tryashtar/image-map/releases/tag/v1.13
