### ISSUE TITLE
Will Not Work With Minecraft Bedrock 1.12

### ISSUE THREAD

**Issue by GrantFBG** [tryashtar/image-map#43]
I Am Selecting My World Through The Bedrock Button, Importing My Picture, And Then Sizing It To A 7x4 Map. However, The Maps Are Not Going To My Inventory And Seem To Be Overwritten By Where I Am At. I Am In A Creative World, With No Resources Installed.

**Comment by tryashtar** [comment]
Can you export your world and send me the mcworld file please?

**Comment by NEMESYS43** [comment]
I am also having this problem I'm just trying to make a 4x4 map it shows that its there in your program but when I try to give my self the map I cant like there are only like 5 maps for some reason and none of them is of my picture

**Comment by tryashtar** [comment]
@NEMESYS43 Can you export your world and send me the mcworld file please?

**Comment by tryashtar** [comment]
@GrantFBG @NEMESYS43 Make sure to close the program (or open a different world) before attempting to open the world in-game. Try doing this and let me know if this fixes the issue or not.

**Comment by 77Z** [comment]
> @GrantFBG @NEMESYS43 Make sure to close the program (or open a different world) before attempting to open the world in-game. Try doing this and let me know if this fixes the issue or not.

This solved the problem for me

**Comment by tryashtar** [comment]
Amazing forward resolve to #48!
(this should now be "fixed" in v1.15)
