### ISSUE TITLE
World corruption on Bedrock

### ISSUE THREAD

**Issue by Zappiestear8069** [tryashtar/image-map#47]
As of now, I am unable to access my world to which I used to make map art on with the program. It keeps saying, "you are out of data storage and space and Minecraft is unable to save your progress! Minecraft will return you to the main menu to clear up storage space." This is a no brainer, but make to make backups when using this program I guess, so when the world is corrupt you won't lose to much progress. Despite that, this program works as intended but is quite slow in loading. Also, for some reason when I look at the existing tab section, it always seems to freeze not only the program but my whole PC its self! Very nice program and coding just have some bug issues.
-Jordanien

**Comment by tryashtar** [comment]
You must close the world in the program before attempting to open the world in-game. Let me know if this fixes your first issue. As for the second, an upload of your mcworld file would be helpful in diagnosing it. Thank you

**Comment by tryashtar** [comment]
Actually, ignore that and try downloading the newest version 1.15:
https://github.com/tryashtar/image-map/releases/tag/v1.15

Let me know if this fixes your issue
