### ISSUE TITLE
No maps were added in game

### ISSUE THREAD

**Issue by Soyuz247** [tryashtar/image-map#49]
I Checked my inventory, it was a total blank, no chest, no map, tried using an empty map, but it overwrites the picture maps ( i checked in the program ) 
As in this attached picture (https://imgur.com/LbpoQKa) you can clearly see that the are some overwrites in map 40 and 41, when they should be part of a face

**Comment by tryashtar** [comment]
Could you upload an attachment of your world please?

**Comment by Soyuz247** [comment]
As in a zipped file?

**Comment by tryashtar** [comment]
Yes that would be much appreciated

**Comment by sircrash** [comment]
same for me
