### ISSUE TITLE
Stuck when loading existing maps

### ISSUE THREAD

**Issue by u3002** [tryashtar/image-map#52]
Minecarft bedrock 1.14
world size: 400+MB 
Created more than 300 maps in my world
Not responding when loading the world
After waiting a few minutes, the program resumes and the pictures can be imported normally

![20200319_144553](https://user-images.githubusercontent.com/20873340/77041622-36789e80-69f5-11ea-9980-dbf816ba6cbc.jpg)
BUT When dragging existing maps list here, The computer will be stuck here, only the mouse can move.
This allowed me to add maps but no way to delete them.

Hope to solve this problem

_------Google Translate_

**Comment by tryashtar** [comment]
Hello, could you attach a copy of your world please?

**Comment by u3002** [comment]
> 您好，您能附上您的世界的副本吗？

I emailed you

**Comment by tryashtar** [comment]
Here is a new version. I've made some heavy loading and transfer optimizations, and halved the memory footprint (also hid blank parent maps, which took up 75% of unneeded space).

[Image.Map.2.zip](https://github.com/tryashtar/image-map/files/4362395/Image.Map.2.zip)

I'm going to push and release this very soon. Until then, please give this version a try and let me know if it is satisfactory. Thank you!

**Comment by u3002** [comment]
> Here is a new version. I've made some heavy loading and transfer optimizations, and halved the memory footprint (also hid blank parent maps, which took up 75% of unneeded space).
> 
> [Image.Map.2.zip](https://github.com/tryashtar/image-map/files/4362395/Image.Map.2.zip)
> 
> I'm going to push and release this very soon. Until then, please give this version a try and let me know if it is satisfactory. Thank you!

![Screenshot](https://user-images.githubusercontent.com/20873340/77218824-7ad97b00-6b6a-11ea-83b8-f0746f6b7d1d.png)
**Unable to import map, reported an error**


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'leveldb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LevelDBWrapper.Interop.leveldb_options_create()
   at LevelDBWrapper.Options..ctor() in D:\Projects\Visual Studio\Image Map 2\LevelDBWrapper\LevelDB.cs:line 221
   at LevelDBWrapper.LevelDB..ctor(String path) in D:\Projects\Visual Studio\Image Map 2\LevelDBWrapper\LevelDB.cs:line 53
   at ImageMap.BedrockWorld.OpenDB()
   at ImageMap.BedrockWorld.LoadMaps()
   at ImageMap.ViewController.OpenWorld(Edition edition, String folder, Boolean bypass_mapwarning)
   at ImageMap.TheForm.OpenWorldWithMessage(Edition edition)
   at ImageMap.TheForm.BedrockWorldButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Image Map 2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Admin/Desktop/Image%20Map%202.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Admin/Desktop/Image%20Map%202.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Admin/Desktop/Image%20Map%202.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
fNbt
    Assembly Version: 0.6.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Admin/Desktop/Image%20Map%202.exe
----------------------------------------
LevelDBWrapper
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Admin/Desktop/Image%20Map%202.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by tryashtar** [comment]
Hm, that is a bit concerning. Did you move the exe out somewhere? It's important that the two DLL files are kept in the same folder as the exe.

**Comment by u3002** [comment]
> Hm, that is a bit concerning. Did you move the exe out somewhere? It's important that the two DLL files are kept in the same folder as the exe.

Nope, all three files are together
-Image Map 2.exe
-leveldb.dll
-zlib1.dll

**Comment by tryashtar** [comment]
Hmm... that is the exact error I get when the DLLs are missing. I'll try to get back to you tomorrow, thanks for your patience

**Comment by jaidon** [comment]
Also getting this same error on the newest release

**Comment by tryashtar** [comment]
I have a new version to try! Please let me know if this version fixes your problems. Thanks for your patience!!

[ImageMap2Test.zip](https://github.com/tryashtar/image-map/files/4391711/ImageMap2Test.zip)

**Comment by jaidon** [comment]
That fixed the issue, thanks!

**Comment by u3002** [comment]
wow, no errors, Thanks for your work

**Comment by tryashtar** [comment]
I'm so glad to hear that! I'll go ahead and close this
