### ISSUE TITLE
Maps don't show an image / Crashing a lot

### ISSUE THREAD

**Issue by Mega1X** [tryashtar/image-map#54]
Hello, this issue has been coming up a lot and I am just wondering if I am doing something wrong. When I open a map I don't get a preview of the map.
![No Preview](https://user-images.githubusercontent.com/9091774/82058093-47126180-9692-11ea-8c95-ab47da8f1c8b.jpg)

This is causing the application to crash a lot. Like a lot a lot. And when I try to select the folder and the images I see nothing.
![Empty](https://user-images.githubusercontent.com/9091774/82058223-71fcb580-9692-11ea-9c57-f67f3d663693.jpg)

Any Ideas?

Thanks

**Comment by tryashtar** [comment]
Thanks for the info. Would you mind uploading here one of the images that's causing problems? And when the application crashes, does it show an error window you can copy/paste from? Both would be quite helpful. Thank you!

**Comment by Mega1X** [comment]
I have an error when I try to press open on the application, and when it does work it doesn't give me a proper window to select things. Like parts of the window are missing
![When Pressing Open](https://user-images.githubusercontent.com/9091774/82074121-45539880-96a8-11ea-8c25-cde9f8d1dc88.png)

Here is the weird thing, every time I try to start the application and then press Open after loading the world it just crashes right away with no error message, sometimes it gives the message above.

**Comment by tryashtar** [comment]
I see. I'll try posting a new version for you shortly!

**Comment by Mega1X** [comment]
Sorry this is the full message in the details

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80070008): Retrieving the COM class factory for component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} failed due to the following error: 80070008 Not enough memory resources are available to process this command. (Exception from HRESULT: 0x80070008).
   at System.Windows.Forms.OpenFileDialog.CreateVistaDialog()
   at System.Windows.Forms.FileDialog.RunDialogVista(IntPtr hWndOwner)
   at System.Windows.Forms.FileDialog.RunDialog(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.CommonDialog.ShowDialog()
   at ImageMap.TheForm.OpenButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Image Map 2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mega3/Desktop/Image.Map.2/Image%20Map%202.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mega3/Desktop/Image.Map.2/Image%20Map%202.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mega3/Desktop/Image.Map.2/Image%20Map%202.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
fNbt
    Assembly Version: 0.6.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mega3/Desktop/Image.Map.2/Image%20Map%202.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by tryashtar** [comment]
Okay, I have a test version for you. Could you please give this version a try and let me know if it fixes the issue? :)

[ImageMap2.zip](https://github.com/tryashtar/image-map/files/4637200/ImageMap2.zip)

**Comment by Mega1X** [comment]
Thanks, 

I just tried it but I'm pressing open and nothing is happening, and when it does open, it gives me a bad menu
![Empty Menu](https://user-images.githubusercontent.com/9091774/82098441-f1aa7480-96d2-11ea-9639-2f9ec8b390ef.png)

Thanks

**Comment by tryashtar** [comment]
Hmm... this is tricky since I can't reproduce the issue on my end. Your PC is having a hard time showing the file dialog for some reason. I made the dialogs get created on click now instead of on startup, no idea if this will change anything:

[ImageMap2.zip](https://github.com/tryashtar/image-map/files/4637375/ImageMap2.zip)

**Comment by Mega1X** [comment]
Ok This is weird. I am loading a blank world, and the window appears normal, but if I try to open my world that has a lot of maps, it seems like it has issues trying to make it work. Is there a limit of how much this is supposed to work?

**Comment by tryashtar** [comment]
Would you mind attaching a copy of the world? It can handle fairly large worlds, but Java maps are a bit slower to read in general

**Comment by Mega1X** [comment]
I wish I can. But this world has some information that I cannot have shared. Its basically a graduation world for students and has names and photos and I can't give that world away. Is there an alternative method? 

Sorry I know you are trying to help but I cant share this world. Not with whats inside.

**Comment by Mega1X** [comment]
I also wanted to state, that this was working in the morning fine, I have a feeling it is the world. So why don't I play around with the other worlds, and see if it fixes anything? I will keep you informed. Thanks a LOT seriously. You devoted your time to help me out and I really appreciate it. I am really sorry to get you working late in the afternoon on a Friday, I am also really sorry for not being able to provide something for you to use. 

Again I will keep you informed let me play around with it some more on another world. and will get back to you.

**Comment by tryashtar** [comment]
No worries, I'm glad I could try to be a bit helpful! Let me know! :)

**Comment by tryashtar** [comment]
Oh, also, if the "open" button continues to inexplicably give you trouble, you can always drag and drop image files directly onto the form. That could help circumvent the problem

**Comment by Mega1X** [comment]
You are amazing. Thank you so much. Seriously.

**Comment by Mega1X** [comment]
Hey Tryashtar,

Thanks for the drag and drop method, its a lot easier, and fewer maps are failing to load.

I just have two questions, maybe I'm doing this wrong. SO when I load the maps and send them to inventory I sometimes still see the older chests reappear even after I destroyed them in creative with the old maps, and the save I was in would revert back to a previous place. It isn't a complete revert. Its basically moving me back 5 spaces where I was too when I sent the first maps into inventory.

Second, when I right-click a new map it replaces some pictures with a proper map, is there something I should do beforehand when making these maps?

Thanks, and as always you are awesome for this application.

**Comment by tryashtar** [comment]
Yeah, for Java Edition worlds, it loads your `level.dat` (player data) when you first open the world, and won't detect changes that Minecraft makes after the fact unless you reopen it. If that's annoying, I can change it to reload after every operation like Bedrock worlds do.

And I don't think I understand your second question. Do you mean right-clicking on an empty map in-game overwrites existing imported maps?

**Comment by Mega1X** [comment]
Yes, right-clicking in-game overwrites exactly so. Sorry, I didn't explain it properly. 

I don't want to trouble you with the Java reload, you've already helped me with this immensely but If it's at all possible that would be great!

**Comment by tryashtar** [comment]
Thanks for the info! All done, please try out the new version :)

https://github.com/tryashtar/image-map/releases/tag/v1.19

**Comment by Mega1X** [comment]
You are awesome :)

**Comment by Mega1X** [comment]
Hey Man,

Sorry to comment again, but I'm finding the application doesn't like the world I'm in. It constantly crashes when I load that specific world and doesn't crash when I load others. Is there a way for me to find out what's crashing the world.

**Comment by Mega1X** [comment]
It basically says its out of memory

**Comment by Mega1X** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80040111): Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
   at Microsoft.WindowsAPICodePack.Dialogs.CommonOpenFileDialog.InitializeNativeFileDialog()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at ImageMap.WorldWindow.BrowseButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Image Map 2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mega3/Desktop/Image.Map.2/Image%20Map%202.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mega3/Desktop/Image.Map.2/Image%20Map%202.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mega3/Desktop/Image.Map.2/Image%20Map%202.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
fNbt
    Assembly Version: 0.6.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mega3/Desktop/Image.Map.2/Image%20Map%202.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by tryashtar** [comment]
It seems like it's dying on your computer when it tries to create the file browser dialogs (created by the open button for images, and the browse button for the world selector).

Unfortunately, that error occurs in code that I didn't write, so I might not necessarily be able to fix it. However, I did look online and found these two useful links:
https://stackoverflow.com/a/34246500
https://github.com/dotnet/winforms/issues/2993

With those, I was able to reproduce your crash when setting reduced color mode in the program compatibility settings, and I may have found a fix. The program should now attempt to fall back to earlier dialogs when the modern ones aren't supported. Please give this test version a try and let me know if it works for you as well:

[Image Map 2.zip](https://github.com/tryashtar/image-map/files/4660616/Image.Map.2.zip)

**Comment by Mega1X** [comment]
Yeappers. Working! Hooray!!

You are awesome!

**Comment by Mega1X** [comment]
Hey Tryashtar,

Is there a way to enable drag and drop, because I can't seem to drag and drop anymore lol

**Comment by tryashtar** [comment]
I didn't change anything about that, it still should work (and does for me)

**Comment by Mega1X** [comment]
That is so weird. Why is my computer so annoying lol, when I try to drag and drop i have a circle with a cross.

**Comment by tryashtar** [comment]
I wonder, are you dragging in from a web browser or something? It only lets you drag local files. But with this version, you can paste both files and raw image data if you copy to clipboard and ctrl-V on the form:

[ImageMap2.zip](https://github.com/tryashtar/image-map/files/4664129/ImageMap2.zip)

**Comment by Mega1X** [comment]
I swear it has to be my computer. Or my world or both, the file you gave me with the falling back to earlier dialogues is crashing again. ARRRGGGG I hate my world.

This graduation world is a pain lol

**Comment by Mega1X** [comment]
Hey Tryashtar, this is the error I am getting when uploading the image.
![Error ](https://user-images.githubusercontent.com/9091774/82632586-af979c00-9bc6-11ea-862a-f878f756cfc2.jpg)

**Comment by Mega1X** [comment]
Hi Tryashstar, Me again. Bummer right!

Sorry about all this, but I have tested something and Its working but I want your input on it. So it is the world I think it has too many maps. So I copied and pasted the maps into a new folder, delete some map files from Data, and rename the new maps to the after the last number in the folder. So basically my maps are at 1699 so I rename the pictures to 1700. Then I send all to inventory and I paste the old info back in. Are there any issues from doing that?

Also this is the error I get when I try to paste a small image. I have a feeling its the world. and it has too many maps. Sorry about causing so much trouble for your app. I want you to know even with the hiccups, this app saved me a TON OF TIME. SO THANK YOU!
<img width="277" alt="Error 2" src="https://user-images.githubusercontent.com/9091774/82670727-b0065600-9c0b-11ea-9e43-9e8ad7ae00ce.png">

**Comment by tryashtar** [comment]
I'm going to try my best to reduce the memory consumption of images, and possibly add a button to load in existing world maps in chunks, instead of always loading all of them, especially if there's thousands in the world.

However, this is going to take some time, possibly a few weeks. Until then, your solution of moving the DAT files out of the world while using the program is a pretty good one. I would recommend leaving the map with the highest number inside the folder, then you shouldn't have to rename anything after the fact.

**Comment by Mega1X** [comment]
Thanks a lot Tryashtar. No worries. I can live with this temp solution. Thanks again for the help seriously, I appreciate everything. I need to buy you a virtual lunch. Just know all this is helping me create a virtual graduation world for our students, and I will be sure to thank you personally! For helping me out with this. #1 Guy!

**Comment by tryashtar** [comment]
@Mega1X I have returned! New version 3.0 loads in 50 maps on the world side, and you can load more by pressing buttons. It still keeps track of which IDs are safe, so no worries about that. There are lots of other improvements too.

https://github.com/tryashtar/image-map/releases/tag/v3.0

Let me know if this helps :)

**Comment by Mega1X** [comment]
Thank You! The graduation world was shown to most of the students and they loved it I hear. I appreciate it and I will use this to make the world even better. Thanks for all your help!

**Comment by tryashtar** [comment]
I'm so happy to hear that!
