### ISSUE TITLE
Unexpected exception while exporting existing map on Bedrock Edition.

### ISSUE THREAD

**Issue by TechnoRunner18** [tryashtar/image-map#55]
Error below when exporting to player via UUID. i got the chest but when I open it the game crashes.
I would try to replace exporting with chests and use shulker boxes instead.

https://hastebin.com/ikehesuxal.sql

**Comment by tryashtar** [comment]
Thank you, will try to fix this shortly

**Comment by tryashtar** [comment]
Okay, please give this version a try and let me know if it works! Thanks! :)

[ImageMap2.zip](https://github.com/tryashtar/image-map/files/4637215/ImageMap2.zip)
