### ISSUE TITLE
Can't load my BE world

### ISSUE THREAD

**Issue by Harry0984** [tryashtar/image-map#58]
Error message : Could not open this world. Perhaps it's the wrong edition, or is missing some important files. 'Could not find C:\users\name\Desktop\mapname\db\levelname.txt'

I'm using the latest version. I used this program a few days ago and succeeded in BE worlds. However, today I failed loading all the maps from BE. Java mode has no problem. It works well today. Please solve it for me

**Comment by tryashtar** [comment]
Hm, the desktop is a peculiar place to have a Bedrock world; usually they're in `%localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds`

But regardless, I think the issue might be confusion about the poorly-labelled "browse" button. You want to select the folder that _contains_ your worlds, not an actual individual world folder. So if you see this:
![image](https://user-images.githubusercontent.com/26075577/83918701-82a2c780-a736-11ea-9f13-0d907e75cc03.png)
then you went one level too deep. You want to choose the folder above so you see this:
![image](https://user-images.githubusercontent.com/26075577/83918765-9ea66900-a736-11ea-9486-bbf2302987c6.png)

Let me know if this helps at all

**Comment by Harry0984** [comment]
Oh, you got the point exactly I wanted to ask! Thank you so much and it does work well right now. Thank you so much!!

**Comment by tryashtar** [comment]
Great, glad I could help! :)
