### ISSUE TITLE
1.16 Snapshot maps have "missing files" 

### ISSUE THREAD

**Issue by DefinitelyQuartz** [tryashtar/image-map#59]
![image](https://user-images.githubusercontent.com/66527700/83949639-eacbd900-a81c-11ea-85dd-b470de285fd8.png)

**Comment by tryashtar** [comment]
Thanks for reminding me about this. I need to manually update the NBT library to support long array tags. I've already done it in a separate project.

**Comment by tryashtar** [comment]
Please let me know if this version fixes the problem without introducing any other issues :)
[ImageMap2.zip](https://github.com/tryashtar/image-map/files/4740826/ImageMap2.zip)

**Comment by DefinitelyQuartz** [comment]
> Please let me know if this version fixes the problem without introducing any other issues :)
> [ImageMap2.zip](https://github.com/tryashtar/image-map/files/4740826/ImageMap2.zip)

Thank you!

**Comment by DefinitelyQuartz** [comment]
For some reason, everytime I use the program all maps now make a new one whenever I try giving myself that map. I've tried deleting player data, I've manually deleted map data. This bug keeps persisting.
Here's a link to me showing you what happens.
https://youtu.be/H0EDOlC4fy4

A new map file gets created in that world folder.

**Comment by tryashtar** [comment]
Great! Oh and by the way, do watch out for this issue in the snapshots:
https://bugs.mojang.com/browse/MC-185417

**Comment by DefinitelyQuartz** [comment]
> Great! Oh and by the way, do watch out for this issue in the snapshots:
> https://bugs.mojang.com/browse/MC-185417

will do, I'll create a seperate issue for the thing above.
