### ISSUE TITLE
When giving a map, a new map is created and instead gives that one. (1.16 pre-release 2)

### ISSUE THREAD

**Issue by DefinitelyQuartz** [tryashtar/image-map#60]
Here's a link to me showing you what happens.
https://youtu.be/H0EDOlC4fy4

Tl;Dr A new map file gets made inside of my maps folder in every world. Doesn't matter if updated or not. Not sure if it might be just my system

**Comment by tryashtar** [comment]
Yeah this is #57, a vanilla bug in the snapshots. We'll just have to wait until it's fixed, probably next prerelease or so

**Comment by tryashtar** [comment]
(Sorry I didn't mention that there was already an issue here for that problem, hahaha!)

**Comment by DefinitelyQuartz** [comment]
I'm sorry for making a duplicate, I wasn't aware of the bug ahah..
