### ISSUE TITLE
Bedrock function doesn't work

### ISSUE THREAD

**Issue by GitHub-User-3** [tryashtar/image-map#65]
When ever I try to run the bedrock version, it gives an eror.

**Comment by tryashtar** [comment]
What's the error?

**Comment by cole00cole00** [comment]
![imagemaperror](https://user-images.githubusercontent.com/73656869/97595723-16639000-1a58-11eb-9bcb-4c1b37ede66e.PNG)
I get this error though the files are all unzipped in same folder and i copied world folder ito the same as well - world shows in the options to click but when i double click as it says the error pictured pops up

**Comment by tryashtar** [comment]
Thank you. Unfortunately, DLL errors like that are very difficult for me to fix unless I can reproduce it myself, which I can't at the moment. I'm curious which version of Windows you're using

**Comment by cole00cole00** [comment]
Windows 7. I transfered world files from my phone as thats what i use to
play and like no other tool claims to work with bedrock.. :(

**Comment by tryashtar** [comment]
Mm, yeah, sorry about that. I suppose Windows 10 is required. I get the same error on a virtual Windows 7, not much I can do about it since Bedrock is Windows 10 edition after all

**Comment by GooseGoHONK** [comment]
I just downloaded the program and have the exact same problem despite using windows 10. All are files in the unzipped folder. Same error message as shown above.

**Comment by tryashtar** [comment]
Thanks. These issues with leveldb are very hard for me to investigate and solve

**Comment by GooseGoHONK** [comment]
:/ shame, I was really hoping to use it. Can't seem to find any other programs like it that will work for bedrock. Any way I can help resolve it? It would really be of great use to me

**Comment by GooseGoHONK** [comment]
or do you know of another program that does the same thing?

**Comment by tryashtar** [comment]
@GitHub-User-3 @cole00cole00 @GooseGoHONK Hey, I looked into this and may have solved it (works for me now on Windows 7).
Please download this version and try, and let me know what happens: 
[Image Map TEST VERSION.zip](https://github.com/tryashtar/image-map/files/5521290/Image.Map.TEST.VERSION.zip)

**Comment by GooseGoHONK** [comment]
Not getting the error message now!

**Comment by GooseGoHONK** [comment]
It all works perfectly. Nice and simple to use too. love it

**Comment by cherrycinema** [comment]
i had the same problem all of a sudden and downloaded the test version u linked, works fine! thank you for your contribution to the java/bedrock community
