### ISSUE TITLE
Not working on 1.16.1 version map

### ISSUE THREAD

**Issue by AndiSlash0723** [tryashtar/image-map#66]
Hi, thanks for your great work. I love it so much and it helps me alot!

Recently I'm hosting a 1.16.1 Paper server. However, the editor seems doesnt work on 1.16.1's maps.

Please add 1.16.1 map support into it. I really love it and need it :D

Thanks!!!

**Comment by AndiSlash0723** [comment]
![image](https://user-images.githubusercontent.com/47967939/86515736-c67c1000-be4d-11ea-99e8-e7b56552bbc1.png)
This is the message I got when opening a 1.16.1 map

**Comment by tryashtar** [comment]
Thanks for the report. Actually I already fixed this (#59), I just haven't posted a new release yet, sorry about that! I will upload the new version very soon. Until then, this version should have the fix. Give it a try!
[ImageMap2.zip](https://github.com/tryashtar/image-map/files/4875285/ImageMap2.zip)

**Comment by AndiSlash0723** [comment]
I've tested it and it works great just like before. Thank you for the great work sir!!

**Comment by tryashtar** [comment]
Great, glad it worked! :)
