### ISSUE TITLE
Random Images stop converting by convert a huge amount of images

### ISSUE THREAD

**Issue by MilitaerMilitz** [tryashtar/image-map#69]
When converting a huge amount of pictures (in this case 20) random images stop making progress.
The pictures have a resolution of 640x512 pixels.

![Unbenannt](https://user-images.githubusercontent.com/69317314/89556914-58db4f00-d812-11ea-8e5d-d233d4964894.PNG)

This are the settings the images have used.
![Unbenannt2](https://user-images.githubusercontent.com/69317314/89557362-fa62a080-d812-11ea-822e-9ca208b834c9.PNG)

**Comment by tryashtar** [comment]
Hm, unfortunately I can't reproduce this. Not sure what to do

**Comment by tryashtar** [comment]
4.0 should fix this!
