### ISSUE TITLE
Overwrite maps are not update preview

### ISSUE THREAD

**Issue by LC-Jonson** [tryashtar/image-map#71]
After I import some new image to overwrite the old existing maps, those new image didn't show in 'Existing Maps' tab. If I click 'Java World' and reload same world again, it solve but this solution is inconvenience. May you fix it?

**Comment by tryashtar** [comment]
Thank you for letting me know, I fixed this in the latest version:
https://github.com/tryashtar/image-map/releases/tag/v3.3
