### ISSUE TITLE
[Suggestion] Choose a map id when we upload an image

### ISSUE THREAD

**Issue by barraIhsan** [tryashtar/image-map#72]
It will be cool if we can make a 2x3 map (For Example)
![image](https://user-images.githubusercontent.com/57800056/103341268-0b10fd00-4ab9-11eb-9971-07f57b7d6950.png)
Then if we upload an image, then there is an option to choose what map id to start with, so we can replace it
![image](https://user-images.githubusercontent.com/57800056/103341255-02b8c200-4ab9-11eb-80fb-b81bab7a840b.png)

**Comment by barraIhsan** [comment]
But you should do it of each single image (if you have like 2x3 map)

**Comment by tryashtar** [comment]
Hm, I don't think I understand then. Your 2x3 map image up there looks like all of the same map, so there wouldn't be any way to replace each with unique different maps besides manually inserting the new ones.

**Comment by barraIhsan** [comment]
No, so you can place them first, and then replace it

**Comment by SquareCat2008** [comment]
If i upload world it says error level db something
How to solve this

**Comment by SquareCat2008** [comment]
Plz reply
