### ISSUE TITLE
Add to inventory only shows local player Bedrock

### ISSUE THREAD

**Issue by carperaj2021** [tryashtar/image-map#75]
I am trying to add the new map into a certain players inventory. I am hosting a bedrock dedicated server. The only option I have is to give to local player but there is no local player. We are all playing from console and connecting in to the dedicated server.

**Comment by tryashtar** [comment]
Got a copy of the world you can upload?

**Comment by carperaj2021** [comment]
I wasn't sure how I could upload the world so I made a zip file of the world and uploaded to my google drive. [Here](https://drive.google.com/file/d/1Sr7938GrLygZ94RiUpe35TCrmWC4Q0EY/view?usp=sharing) is a link for that. I appreciate the help.

**Comment by tryashtar** [comment]
Fixed, thanks for the report and your world
https://github.com/tryashtar/image-map/releases/tag/v3.4

**Comment by carperaj2021** [comment]
This was awesome return time. I really appreciate the effort.

**Comment by carperaj2021** [comment]
Just a quick update to this, I can't seem to find a way to translate the uuid to xuid or player name. This wouldn't be needed for Java because there are online generators. I just want to insure i'm not messing with any other player's inventory if I give maps to one specific player. I would also be happy if it was possible to place a chest in the sever spawn area and then that player could claim it. If this is too far out of reach I can attempt to figure it out with guessing and checking but I thought this would be a nice feature.

**Comment by tryashtar** [comment]
Yeah, I tried to find a way to find the player's IGN from their UUID, but I don't think bedrock caches that information in the world save (surprising considering how much actually useless data it does save). And querying an API for it would just be a headache. I'll try to look into making it a bit better though

**Comment by carperaj2021** [comment]
I ended up using MCCToolchest to look through inventories of each player until I found the correct UUID. Thank you for the help.
