### ISSUE TITLE
[Suggestion] Improve export capabilities

### ISSUE THREAD

**Issue by Toseflo** [tryashtar/image-map#76]
I use image-maps because of its great user-interface and easy to use dithering function to improve images for Minecraft. I play on a server, so I can't send images directly to the world. Instead after converting, I have to send them to a world first and then in the Existing Maps tab, I can export the map as an image.
My first sugesstion would to be able to export images after converting them without having to send them to a world first.

My second issue is with bigger maps. When I export them, they are exported as many separated files. On the server we use a plugin to download images from the internet and convert them to maps. So when I have multiple image files, I first have to merge them into one image file, which I can then upload and use on the server.
It would be great if you could add a way to export a whole converted image as one file. I'm probably not the only one who would benefit from this change. (Or is there another program which only improves images for Minecraft and doesn't create maps? Because I haven't found one :'D)

Nevertheless, I really like this tool!

**Comment by tryashtar** [comment]
Added both in 4.0! Can export images of maps in the import tab, and can export an entire grid as one image!
