### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by gaigncisic** [tryashtar/image-map#77]
I don't know if it's my problem or the image-map. I can't find anything it says to do and I'm trying to do it for bedrock.

**Comment by tryashtar** [comment]
I'd love to help but I'll need a bit more information

**Comment by gaigncisic** [comment]
"Firstly: download, unzip, and run the application" what application?

**Comment by gaigncisic** [comment]
nv i found it

**Comment by tryashtar** [comment]
So, all good then? :)
