### ISSUE TITLE
Request, not issue - can you update it to store more map files?

### ISSUE THREAD

**Issue by wefsda** [tryashtar/image-map#78]
Currently the program crashes when there are several thousand map files - if you can make it in such a way that could slowly load and store thousands on thousands of files, then it could have incredible applications - such as a 4k video player in minecraft using command blocks and item frames w/ maps.

**Comment by Max-RM** [comment]
> Currently the program crashes when there are several thousand map files - if you can make it in such a way that could slowly load and store thousands on thousands of files, then it could have incredible applications - such as a 4k video player in minecraft using command blocks and item frames w/ maps.

such a program for transferring video to minecraft was developed by me, but it only works together with other programs (also image map), although it allows you to transfer video to the world with a size of 128×128 pixels and 10 frames per second

https://github.com/Max-RM/Map-Art-Video-cassettes-editor   

https://youtu.be/7TJ9HorxLuI

**Comment by Max-RM** [comment]
I also asked Tryashtar to fix the image map, but he said
https://github.com/tryashtar/image-map/issues/90

**Comment by tryashtar** [comment]
4.0 should work with thousands of maps just fine!
