### ISSUE TITLE
Help me pls bro 

### ISSUE THREAD

**Issue by senpaikendall** [tryashtar/image-map#79]
Pls help me its saying error opening that world: DIINotFoundException: Unable to load DLL 'leveldb.dll': The specified module could be found. (Exception from HRESULT: 0x8007007E) pls help me as soon as possible

**Comment by tryashtar** [comment]
Check out #65

**Comment by senpaikendall** [comment]
i did but it doesnt work i use windows 10and it doesnt work

**Comment by senpaikendall** [comment]
java works but bedrock doesnt
