### ISSUE TITLE
Chest Alert with empty inventory

### ISSUE THREAD

**Issue by almightymixon** [tryashtar/image-map#81]
when i try to send maps to my world, it gives me the chest alert and my inventory is empty, i dont know if iam doing something wrong.

**Comment by tryashtar** [comment]
What chest alert do you mean?

**Comment by almightymixon** [comment]
![Screenshot 2021-03-04 113323](https://user-images.githubusercontent.com/80020968/110019581-7e173980-7cdd-11eb-8a92-207f13a12294.png)

**Comment by tryashtar** [comment]
Huh that's strange, would you mind uploading a copy of the world here so I can check it out?

**Comment by almightymixon** [comment]
im not sure i know how

**Comment by almightymixon** [comment]
its a realm, not sure if thats a problem

**Comment by tryashtar** [comment]
If it's a realm, I'm pretty sure it's not even saved to your PC at all, so I don't know how you're even accessing it with Image Map.

**Comment by almightymixon** [comment]
well it lets me download the world and access it on image map but when i go to the folder it doesn't come out

**Comment by tryashtar** [comment]
Ah well if it lets you download the world then can I get a copy of it to check out? 😁
