### ISSUE TITLE
World error!

### ISSUE THREAD

**Issue by Themasterofgam3** [tryashtar/image-map#84]
Whenever I loaded up the Xbox world that I just exported it doesn't even show the world it just shows db so I double click it and it says Error opening that world: Exception: Invalid argument: F:\Name of the world\db\db: does not exist (create_if_missing is false) Please Help. There is a picture below.

![error](https://user-images.githubusercontent.com/47432874/111052758-dd86ef00-842b-11eb-80cc-10964ff4a8ca.PNG)

**Comment by tryashtar** [comment]
Yeah, sorry, it's a bit confusing. But when you click "select saves folder," it wants you to choose the folder that *contains* your world, not your world itself

**Comment by Themasterofgam3** [comment]
So make a folder and but the world inside the folder then try it.
