### ISSUE TITLE
in need of help error when trying to open MCBE Worlds

### ISSUE THREAD

**Issue by gituser245** [tryashtar/image-map#85]
![Στιγμιότυπο οθόνης 2021-05-17 201635](https://user-images.githubusercontent.com/84343022/118530658-91b73580-b74d-11eb-85d5-7ff7557104f4.png)
i get this error when i try to open minecraft bedrock worlds i tried using a different version of the game, creating new worlds and using older versions of the program but same issue.

**Comment by tryashtar** [comment]
I'm sorry, I don't know how to help with this error
