### ISSUE TITLE
Issue with world loading.

### ISSUE THREAD

**Issue by sneakysandcrab** [tryashtar/image-map#86]
Found Image Map 3 because was tryin to restore the legacy chunk version so that i may be able to get UMCE to work.

When tryin to access the world folder, i get this error.

![Untitled](https://user-images.githubusercontent.com/85461409/120941342-c7fe2a00-c6e7-11eb-9a0c-fc5205bfec85.png)

any idea what might cause it?

im pulling my world using an ftp off of my server. not a realm.

**Comment by tryashtar** [comment]
Mind uploading your world here for me to check out?

**Comment by sneakysandcrab** [comment]
apparently even the compressed file wont upload on here. any chance i could upload it some other way?

**Comment by tryashtar** [comment]
MediaFire or Google drive would work
