### ISSUE TITLE
error open world minecraft pe v 1.2.8

### ISSUE THREAD

**Issue by Max-RM** [tryashtar/image-map#87]
image map works fine with the worlds of minecraft pe 1.16.20.03 and minecraft for windows 10 1.16.100.04 and minecraft education edition 1.14.50. but it can't open the worlds of minecraft pe version 1.2.8. although MCCToolChestPE can handle this task unlike image map. my request is to add support for bedrock Edition world version 1.2.8 even though it is a fairly old version.

**Comment by tryashtar** [comment]
Would you mind uploading a world from this version for me to check out?

**Comment by Max-RM** [comment]
> Would you mind uploading a world from this version for me to check out?

ok. here is my zip archive with the world created in minecraft pocket edition 1.2.8
[World 1.2.8.zip](https://github.com/tryashtar/image-map/files/6664631/World.1.2.8.zip)

**Comment by tryashtar** [comment]
![image](https://user-images.githubusercontent.com/26075577/122302730-c25ecc00-cebf-11eb-85d0-9a480e975a27.png)
Huh that's odd, I was able to load your world in image map just fine, and it got the version right. I added maps too just fine. Although opening it in-game seemed to reset the world.

**Comment by Max-RM** [comment]
> ![image](https://user-images.githubusercontent.com/26075577/122302730-c25ecc00-cebf-11eb-85d0-9a480e975a27.png)
> Huh that's odd, I was able to load your world in image map just fine, and it got the version right. I added maps too just fine. Although opening it in-game seemed to reset the world.
didn't work for me. okay, I'll close the issue. anyway, thank you for your amazing program.

**Comment by Max-RM** [comment]
> ![image](https://user-images.githubusercontent.com/26075577/122302730-c25ecc00-cebf-11eb-85d0-9a480e975a27.png)
> Huh that's odd, I was able to load your world in image map just fine, and it got the version right. I added maps too just fine. Although opening it in-game seemed to reset the world.

didn't work for me. okay, I'll close the issue. anyway, thank you for your amazing program.
