### ISSUE TITLE
error when transferring a lot of images (not all images are loaded)

### ISSUE THREAD

**Issue by Max-RM** [tryashtar/image-map#90]
hi tryashtar. I found an error that is not being fixed. when transferring a large number of images to the world of minecraft bedrock, an error occurs due to which some of the images are not transferred to the world and remain unloaded.

![20210630_104400](https://user-images.githubusercontent.com/81485476/123908611-79307100-d9c3-11eb-9080-d109b6b6253a.jpg)

![20210630_104248](https://user-images.githubusercontent.com/81485476/123908590-72a1f980-d9c3-11eb-9323-164d9096a213.jpg)

even if I wait a few hours, they still won't load.
can you fix this error?

I want this error not to happen, because when transferring 46080 images, many will not load.

**Comment by tryashtar** [comment]
Hey there. This program, and really winforms as a whole, is not very memory-efficient when it comes to images. Transferring that many images at one time is basically sure to kill all the threads. I do have vague plans to switch to a different library, but unfortunately development on this program isn't a huge priority for me now

**Comment by Max-RM** [comment]
> Привет. Эта программа, как и winforms в целом, не очень эффективно использует память, когда дело касается изображений. Передача такого количества изображений за один раз, по сути, убьет все потоки. У меня есть смутные планы по переходу на другую библиотеку, но, к сожалению, разработка этой программы сейчас не является для меня огромным приоритетом.

**Comment by Max-RM** [comment]
damn. this is the only program that allows me to transfer videos to minecraft.

if the program worked incorrectly and some frames are not transferred, then some frames are missing in the finished video. moreover, in a video with 10 fps, the skipping of frames is very noticeable.

**Comment by Max-RM** [comment]
> Hey there. This program, and really winforms as a whole, is not very memory-efficient when it comes to images. Transferring that many images at one time is basically sure to kill all the threads. I do have vague plans to switch to a different library, but unfortunately development on this program isn't a huge priority for me now

Tryashtar can you implement this in another way? for example, reloading unloaded images while preserving the correct uuids. this way you don't have to create another library

**Comment by Max-RM** [comment]
> Hey there. This program, and really winforms as a whole, is not very memory-efficient when it comes to images. Transferring that many images at one time is basically sure to kill all the threads. I do have vague plans to switch to a different library, but unfortunately development on this program isn't a huge priority for me now

I'm sorry, I may be speaking incorrectly, because I use a translator

**Comment by Max-RM** [comment]
> Hey there. This program, and really winforms as a whole, is not very memory-efficient when it comes to images. Transferring that many images at one time is basically sure to kill all the threads. I do have vague plans to switch to a different library, but unfortunately development on this program isn't a huge priority for me now

please tell me what is the name of the library that is responsible for transferring images.

**Comment by tryashtar** [comment]
System.Drawing

**Comment by Max-RM** [comment]
> System.Drawing

Thank you

**Comment by tryashtar** [comment]
Should be fixed with 4.0!
