### ISSUE TITLE
error with the name of the folder containing the world and the location of the world

### ISSUE THREAD

**Issue by Max-RM** [tryashtar/image-map#91]
if the folder containing the world is named not in English letters, but for example in Russian, then image map cannot open the world.
also, if the world is not on disk C but on disk D or any other disk, the program also cannot open the world

I think it will not be difficult for you to fix this errors

**Comment by tryashtar** [comment]
Sorry, this is yet another issue with leveldb. I looked why it happens, and I found that we are forced to use `CharSet.Ansi`, which passes the string over to C code and completely mangles unicode. I have no idea how to fix this, sorry. I hate C.

**Comment by tryashtar** [comment]
Should be fixed with 4.0!
