### ISSUE TITLE
SEHException

### ISSUE THREAD

**Issue by perpatrik79** [tryashtar/image-map#92]
![image](https://user-images.githubusercontent.com/46899914/132805089-d6487ace-fa07-4433-9f6a-157ff6a8c9ef.jpg)
Hi!
I get an SEHException when trying to load my bedrock worlds. Any idea as of what can be the cause?

**Comment by Kybomaster** [comment]
https://github.com/tryashtar/image-map/issues/93#issuecomment-917595200

**Comment by Kybomaster** [comment]
The solution to the problem. You must remove all non-English symbols lying on the way to your world. That is, no folder in its name should contain non-English characters
