### ISSUE TITLE
External component threw an exception

### ISSUE THREAD

**Issue by PrograMistV2** [tryashtar/image-map#93]
![IMG_20210912_112846](https://user-images.githubusercontent.com/65886298/132979679-5028a008-7fb4-432e-9b9c-49ec9f77a01c.jpg)
When i try to load the bedrock world, the program gives this error.
I tried loading worlds with different versions, from 1.14 to 1.17.30, but the program still gives an error.

**Comment by PrograMistV2** [comment]
Oh ... I found a solution to this problem, the fact is that I transferred my worlds from my phone and saved them in a folder on my desktop, if someone has a similar problem, then do not repeat my mistakes. You need to save worlds along the path: C: \ Users \ [username] \ AppData \ Local \ Packages \ Microsoft.MinecraftUWP_8wekyb2d8bbwe \ LocalState \ games \ com.mojang \ minecraftworlds \

Thanks for the great program

**Comment by Kybomaster** [comment]
Можешь поподробнее рассказать?
