### ISSUE TITLE
Crash when Load All - Custom loading range, maybe?

### ISSUE THREAD

**Issue by Kinboise** [tryashtar/image-map#94]
ImageMap3 has been very useful to me, and my world has ~1500 maps. Now the program crashes when I click on `Load All` (MCBE 1.17.10), while `Load More` is OK. I guess it might be some memory usage issue.

I do need to find and overwrite some old maps frequently (the terminal sign map, for example, after I built a new station). 5 maps per click is too slow, while loading all isn't necessary either.

Would it be possible to add a `Load Custom Range` button, where I can manually input a range of maps to load, so that I don't have to load all the newer maps before I get to the old one needed (also the program won't crash)?

**Comment by tryashtar** [comment]
Sorry for the crashes, and thanks for the suggestion. A "load custom range" button is viable, but if you're just overwriting, it should let you do that even if the existing map isn't loaded yet.

Unfortunately, it will be a long while before I'm able to continue work on this.

**Comment by tryashtar** [comment]
4.0 should load all maps without crashing!
