### ISSUE TITLE
Wrong work on Linux.

### ISSUE THREAD

**Issue by N08I40K** [tryashtar/image-map#97]
After importing a picture, an empty map file is created in the data world folder, when entering the world and taking a map, it writes this: 
![image](https://user-images.githubusercontent.com/55545594/148708091-fa1c42ba-97f1-412d-aa40-e28b293747b6.png)

**Comment by tryashtar** [comment]
Weird, would you mind posting the image you used, and the map .dat file created (ideally before opening the world in-game)? Thanks!
