### ISSUE TITLE
Crop to fill frame option?

### ISSUE THREAD

**Issue by StrikerMan780** [tryashtar/image-map#98]
Could we get a "crop to frame" option? Perhaps with the ability to reposition the image within the frame?

**Comment by tryashtar** [comment]
I'm not sure I understand the request. What would this do?

**Comment by StrikerMan780** [comment]
Crop the image to fill the frame instead of stretching? Don't really know how to get more clear than that.

**Comment by tryashtar** [comment]
Ah, so instead of leaving extra space inside the frames, have the image get cut off on the longer side. Yeah I could probably do that. But sadly I probably won't get around to it for a while

**Comment by StrikerMan780** [comment]
Yeah, that's it. No rush.

**Comment by PlainsVillager** [comment]
on

**Comment by tryashtar** [comment]
Added with 4.0!
