### ISSUE TITLE
Request/query: Education Edition? can it happen? 

### ISSUE THREAD

**Issue by DottyButton** [tryashtar/image-map#99]
Hi.
Wondering if there is any way you (or I) could make it work to upload map images to Education Edition? 

I am sure there is an obvious barrier that I am not aware of that makes it more difficult, or a workaround I have not found. So asking as much as requesting... on behalf of the community of educators that would love to have this functionality available!

Would love to upload images with educational content that cannot be recreated with blocks or be able to display the student's work in Ed Edition. 

Thank you for your time.

**Comment by tryashtar** [comment]
Were you the same one who emailed me? :P
Regardless, I'll repeat the answer here:
Simply choose "Bedrock World," then "Select Saves Folder," and paste this path: `%appdata%\Minecraft Education Edition\games\com.mojang\minecraftWorlds`

**Comment by DottyButton** [comment]
Yes, it was me. Thanks again!
